"""
UNKNOWN X v2.0 - Document Metadata Service

Purpose:
- Collect metadata from the existing UNKNOWN pipeline.
- Build a standardized metadata dictionary for Document IQ scoring.
- Save metadata reports for dashboard and analytics.

Compatible with:
- document_loader.py
- chunker.py
- config.py
"""

import json
from pathlib import Path

from app.rag.config import settings

# ==========================================================
# Project Paths
# ==========================================================

JSON_DIR = settings.JSON_DIR
CHUNK_DIR = settings.CHUNK_DIR
VECTOR_DIR = settings.VECTOR_DIR
METADATA_DIR = settings.BASE_DIR / "app" / "data" / "metadata"

# Ensure metadata directory exists.
METADATA_DIR.mkdir(parents=True, exist_ok=True)


# ==========================================================
# Read Document JSON
# ==========================================================


def load_document_json(document_name: str) -> dict:
    """
    Load metadata generated by document_loader.py.

    Example:
        sample_ieee.pdf -> datasets/json/sample_ieee.json
    """

    json_file = JSON_DIR / f"{Path(document_name).stem}.json"

    if not json_file.exists():
        raise FileNotFoundError(f"Document JSON not found: {json_file}")

    with open(json_file, "r", encoding="utf-8") as file:
        return json.load(file)


# ==========================================================
# Count Chunks for a Document
# ==========================================================


def count_document_chunks(document_name: str) -> int:
    """
    Count the number of chunks belonging to a document.
    Reads datasets/chunks/chunks.json generated by chunker.py.
    """

    chunk_file = CHUNK_DIR / "chunks.json"

    if not chunk_file.exists():
        raise FileNotFoundError(f"Chunk file not found: {chunk_file}")

    with open(chunk_file, "r", encoding="utf-8") as file:
        chunks = json.load(file)

    return sum(1 for chunk in chunks if chunk.get("document") == document_name)


# ==========================================================
# Metadata Completeness Score
# ==========================================================


def calculate_metadata_completeness(doc_json: dict, chunk_count: int) -> float:
    """
    Calculate metadata completeness (0.0 - 1.0).

    The score checks whether important metadata fields generated by
    document_loader.py and chunker.py are present.
    """

    required_fields = [
        "title",
        "source_file",
        "document_hash",
        "total_pages",
        "total_words",
        "estimated_read_time",
    ]

    available_fields = sum(
        1 for field in required_fields if doc_json.get(field) not in [None, "", 0]
    )

    # Chunk information available.
    if chunk_count > 0:
        available_fields += 1

    total_checks = len(required_fields) + 1

    return round(available_fields / total_checks, 2)


# ==========================================================
# Build Standard Metadata Object
# ==========================================================


def build_document_metadata(document_name: str) -> dict:
    """
    Assemble metadata from the UNKNOWN pipeline.

    This metadata becomes the single source of truth for:
    - Document IQ Score
    - Dashboard
    - Analytics
    - Future document APIs
    """

    doc_json = load_document_json(document_name)
    chunk_count = count_document_chunks(document_name)

    metadata = {
        # --------------------------
        # Identity
        # --------------------------
        "document": doc_json.get("source_file", document_name),
        "title": doc_json.get("title", Path(document_name).stem),
        "document_type": str(doc_json.get("document_type", "unknown"))
        .lstrip(".")
        .lower(),
        "document_hash": doc_json.get("document_hash"),
        # --------------------------
        # Document Statistics
        # --------------------------
        "pages": doc_json.get("total_pages", 0),
        "chunks": chunk_count,
        "text_length": doc_json.get("total_words", 0),
        "estimated_read_time": doc_json.get("estimated_read_time", 0),
        # --------------------------
        # Pipeline Status
        # --------------------------
        "embedding_status": True,  # Verified later using FAISS metadata.
        "ocr_required": False,  # Digital PDFs extracted directly.
        "ocr_quality": 1.0,  # Full OCR score for digital PDFs.
        # --------------------------
        # Metadata Health
        # --------------------------
        "metadata_completeness": calculate_metadata_completeness(
            doc_json,
            chunk_count,
        ),
    }

    return metadata


# ==========================================================
# Save Metadata Report
# ==========================================================


def save_document_metadata(metadata: dict) -> Path:
    """
    Save metadata into app/data/metadata/.

    Example:
        sample_ieee.pdf ->
        app/data/metadata/sample_ieee_metadata.json
    """

    output_file = METADATA_DIR / f"{Path(metadata['document']).stem}_metadata.json"

    with open(output_file, "w", encoding="utf-8") as file:
        json.dump(metadata, file, indent=4, ensure_ascii=False)

    return output_file


# ==========================================================
# Load Saved Metadata
# ==========================================================


def load_saved_metadata(document_name: str) -> dict:
    """
    Load metadata report previously saved by save_document_metadata().
    """

    metadata_file = METADATA_DIR / f"{Path(document_name).stem}_metadata.json"

    if not metadata_file.exists():
        raise FileNotFoundError(f"Metadata report not found: {metadata_file}")

    with open(metadata_file, "r", encoding="utf-8") as file:
        return json.load(file)
